name: Yet-another-Minesweeper-clone setup file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: apt install catch2
    - name: make
      run: make
    - name: make tests
      run: make tests
